################################################################################
# 53_sexual_fecundity_layer.R - Idea 1: Size-threshold sexual fecundity (F_sex)
################################################################################
#
# PURPOSE:
#   Construct the sexual-fecundity row (F_sex) for the A. palmata scenario
#   framework (PRD scenario S1). F_sex assigns sexual-recruit contributions
#   from each reproductive-size adult size class (SC4, SC5) to the SC1 (0-10
#   cm^2) recruit class. This is the foundation layer on which scripts 54
#   (sterility lag) and 55 (lesion penalty) stack additional biological
#   realism. Output feeds directly into scenario assembly in script 60.
#
# HYPOTHESIS:
#   Adding a sexual-reproduction pathway separate from fragmentation shifts
#   lambda and reduces the dominance of SC5 stasis elasticity. Maturity is
#   size-thresholded (Vardi 2011: 90% gamete production at >= 4000 cm^2),
#   gamete production scales with live tissue area via oocyte density
#   (Mendoza-Quiroz 2023: 63.6 oocytes/cm^2), and realised fertilization is
#   95% between unrelated wild gametes (Mendoza-Quiroz 2023).
#
# INPUTS:
#   - 05_data/standardized/apal_life_history_parameters.csv   (LHP CSV)
#       * maturity_threshold          = 4000 cm^2  (Vardi 2011)
#       * fecundity_gonadal_index     = 63.6 oocytes/cm^2 (Mendoza-Quiroz 2023)
#       * reproductive_fertilization  = 95 % wild gametes (Mendoza-Quiroz 2023)
#   - parameter_lists/recruit_surv_pars.rds
#       * s_recruit ~ 0.028 (annualised post-settlement recruit survival,
#         derived from Chamberland 2015 and restoration recruit monitoring)
#
# OUTPUTS:
#   - 06_analysis/output/sexual_fecundity_matrix.rds
#       list(F_sex, parameters, source)
#
# CITATIONS:
#   Vardi et al. 2011         -- 4000 cm^2 maturity threshold (LHP row 2)
#   Mendoza-Quiroz et al. 2023 -- oocyte density and fertilization (LHP rows 4, 32)
#   Chamberland et al. 2015    -- recruit post-settlement survival (via
#                                 recruit_surv_pars.rds generated by script 17)
#
# Author: Detmer & Stier Lab
# Date: 2026-04-17
################################################################################

source("06_analysis/scripts/utils/shared_utilities.R")

print_header("Script 53: Build sexual-fecundity matrix F_sex (S1)")

# --- Paths ---
lhp_path          <- file.path("05_data", "standardized",
                               "apal_life_history_parameters.csv")
recruit_pars_path <- file.path("parameter_lists", "recruit_surv_pars.rds")
output_dir        <- file.path("06_analysis", "output")
out_path          <- file.path(output_dir, "sexual_fecundity_matrix.rds")

if (!dir.exists(output_dir)) dir.create(output_dir, recursive = TRUE)

# --- Load life-history parameters (hard defaults on fallback) ---
DEFAULT_MATURITY    <- 4000   # cm^2,      Vardi 2011
DEFAULT_OOCYTES     <- 63.6   # oocytes/cm^2, Mendoza-Quiroz 2023
DEFAULT_FERT_WILD   <- 0.95   # Mendoza-Quiroz 2023, F1 sperm x wild eggs
DEFAULT_S_RECRUIT   <- 0.028  # Chamberland 2015 / restoration recruits

if (file.exists(lhp_path)) {
  lhp <- read.csv(lhp_path, stringsAsFactors = FALSE)

  pick <- function(param, sub = NULL, divisor = 1) {
    rows <- lhp$Parameter == param
    if (!is.null(sub)) rows <- rows & lhp$Sub_Category == sub
    vals <- suppressWarnings(as.numeric(lhp$Value[rows]))
    vals <- vals[!is.na(vals)]
    if (length(vals) == 0) return(NA_real_)
    vals[1] / divisor
  }

  maturity_size     <- pick("maturity_threshold",         "size_live_cm2")
  oocyte_per_cm2    <- pick("fecundity_gonadal_index",    "oocyte_density")
  fertilization     <- pick("reproductive_fertilization", "wild_gametes",
                            divisor = 100)  # CSV stores percent

  if (is.na(maturity_size))  maturity_size  <- DEFAULT_MATURITY
  if (is.na(oocyte_per_cm2)) oocyte_per_cm2 <- DEFAULT_OOCYTES
  if (is.na(fertilization))  fertilization  <- DEFAULT_FERT_WILD
} else {
  print_warn(sprintf("LHP CSV not found at %s - using PRD defaults", lhp_path))
  maturity_size  <- DEFAULT_MATURITY
  oocyte_per_cm2 <- DEFAULT_OOCYTES
  fertilization  <- DEFAULT_FERT_WILD
}

# --- Load recruit survival (s_recruit) ---
if (file.exists(recruit_pars_path)) {
  recruit_pars <- readRDS(recruit_pars_path)
  s_recruit <- recruit_pars$s_recruit
  if (is.null(s_recruit) || is.na(s_recruit)) s_recruit <- DEFAULT_S_RECRUIT
} else {
  print_warn(sprintf("recruit_surv_pars.rds not found at %s - using default %.4f",
                     recruit_pars_path, DEFAULT_S_RECRUIT))
  s_recruit <- DEFAULT_S_RECRUIT
}

# --- Report inputs ---
print_subheader("Calibrated inputs")
cat(sprintf("  maturity_size      : %.0f cm^2   (Vardi 2011)\n",        maturity_size))
cat(sprintf("  oocyte_per_cm2     : %.2f        (Mendoza-Quiroz 2023)\n", oocyte_per_cm2))
cat(sprintf("  fertilization_rate : %.3f        (Mendoza-Quiroz 2023)\n", fertilization))
cat(sprintf("  s_recruit          : %.4f        (Chamberland 2015)\n",   s_recruit))

# --- Build F_sex via shared helper ---
F_sex <- build_F_sex(
  s_recruit          = s_recruit,
  oocyte_per_cm2     = oocyte_per_cm2,
  fertilization_rate = fertilization,
  maturity_size      = maturity_size
)

print_subheader("F_sex matrix (recruits into SC1 per adult/yr, by adult column)")
print(round(F_sex, 3))

sc1_row_total <- sum(F_sex["SC1", ])
cat(sprintf("\n  SC1 row total (aggregate sexual recruits/adult/yr): %.3f\n",
            sc1_row_total))

# --- Package output ---
parameters <- list(
  maturity_size      = maturity_size,
  oocyte_per_cm2     = oocyte_per_cm2,
  fertilization_rate = fertilization,
  s_recruit          = s_recruit,
  sc4_repr_frac      = 0.3,
  sc5_repr_frac      = 0.9
)

result <- list(
  F_sex      = F_sex,
  parameters = parameters,
  source     = "Vardi 2011 + Mendoza-Quiroz 2023 + Chamberland 2015",
  generated  = Sys.time()
)

saveRDS(result, out_path)
print_success(sprintf("Saved %s", out_path))

cat("\nDone.\n")
